# Title: Plex
# Description: Plex Media Server

services:
  plex:
    image: lscr.io/linuxserver/plex:1.42.2
    container_name: plex
    restart: always
    networks:
      - proxy
    # ports:
      #  - "32400:32400"     # WebUI
      # - "1900:1900/udp"   # DLNA
      # - "5353:5353/udp"   # Bonjour/Avahi
      # - "8324:8324"       # Plex Companion (Roku)
      # - "32410:32410/udp" # GDM Network Discovery
      # - "32412:32412/udp" # GDM Network Discovery
      # - "32413:32413/udp" # GDM Network Discovery
      # - "32414:32414/udp" # GDM Network Discovery
      # - "32469:32469"     # Plex DLNA Server
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-Europe/Berlin}
      VERSION: ${VERSION:-docker}
      PLEX_CLAIM: ${PLEX_CLAIM}
      ADVERTISE_IP: ${ADVERTISE_IP}/
    volumes:
      - ${DIR_DATA}/config:/config
      - ${DIR_MOVIES}:/movies
      - ${DIR_SHOWS}:/tv
    devices:
      - /dev/dri:/dev/dri
    labels:
      # Traefik 3.0
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      # router: plex
      - "traefik.http.routers.plex.entrypoints=https"
      - "traefik.http.routers.plex.rule=Host(`${DOMAIN_PLEX:-plex.pixelstack.live}`)"
      - "traefik.http.routers.plex.middlewares=secured@file"
      - "traefik.http.routers.plex.service=plex"
      - "traefik.http.routers.plex.tls=true"
      - "traefik.http.routers.plex.tls.certresolver=${CERT_RESOLVER:-production}" # staging or production
      # service: plex
      - "traefik.http.services.plex.loadbalancer.server.port=32400"
      # Homepage Dashboard
      - homepage.group=Services
      - homepage.name=Plex
      - homepage.icon=plex
      - homepage.href=https://${DOMAIN_PLEX:-plex.pixelstack.live}
      - homepage.description=Media Server
      - homepage.weight=30
      - homepage.widget.type=plex
      - homepage.widget.fields=["streams", "albums", "movies", "tv"]
      - homepage.widget.url=https://${DOMAIN_PLEX:-plex.pixelstack.live}
      - homepage.widget.key=${HOMEPAGE_VAR_PLEX_KEY}

networks:
  proxy:
    external: true
