# Title: authentik
# Description: Identity provider

services:
  postgresql:
    image: docker.io/library/postgres:17.2-alpine3.19
    container_name: postgresql-authentik
    restart: always
    networks:
      - proxy
      - backend
    # ports:
    #   - 5432:5432  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    environment:
      POSTGRES_DB: ${DB_NAME:-authentik}
      POSTGRES_USER: ${DB_USER:-authentik}
      POSTGRES_PASSWORD: ${DB_PASS:?database password required}
    volumes:
      - ${DIR_DATA}/db-data:/var/lib/postgresql/data

  valkey:
    image: valkey/valkey:8.1.3-alpine
    container_name: valkey-authentik
    command: --save 60 1 --loglevel warning
    restart: always
    networks:
      - proxy
      - backend
    healthcheck:
      test: ["CMD-SHELL", "valkey-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - ${DIR_DATA}/valkey-data:/data

  auth-server:
    image: ghcr.io/goauthentik/server:2025.8.1
    container_name: authentik
    restart: always
    depends_on:
      - postgresql
      - valkey
    command: server
    networks:
      - proxy
      - backend
    ports:
      - "8086:9000"
      - "8087:9443"
    environment:
      AUTHENTIK_REDIS__HOST: valkey
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: ${DB_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${DB_NAME:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${DB_PASS}
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY}
      AUTHENTIK_EMAIL__HOST: ${AUTHENTIK_EMAIL_HOST}
      AUTHENTIK_EMAIL__PORT: ${AUTHENTIK_EMAIL_PORT}
      AUTHENTIK_EMAIL__USERNAME: ${AUTHENTIK_EMAIL_USERNAME}
      AUTHENTIK_EMAIL__PASSWORD: ${AUTHENTIK_EMAIL_PASSWORD}
      AUTHENTIK_EMAIL__USE_TLS: true
      AUTHENTIK_EMAIL__USE_SSL: false
      AUTHENTIK_EMAIL__TIMEOUT: 10
      AUTHENTIK_EMAIL__FROM: ${AUTHENTIK_EMAIL_FROM}
    volumes:
      - ${DIR_DATA}/authentik-data/media:/media
      - ${DIR_DATA}/authentik-data/templates:/templates
    labels:
      # Traefik 3.0
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      # router: authentik
      - "traefik.http.routers.authentik.entrypoints=https"
      - "traefik.http.routers.authentik.rule=Host(`${DOMAIN_AUTHENTIK:-authentik.pixelstack.live}`)"
      - "traefik.http.routers.authentik.service=authentik"
      - "traefik.http.routers.authentik.tls=true"
      - "traefik.http.routers.authentik.tls.certresolver=${CERT_RESOLVER:-production}" # staging or production
      # service: authentik
      - "traefik.http.services.authentik.loadbalancer.server.port=9000"
      # Homepage Dashboard
      - homepage.group=Management
      - homepage.name=Authentik
      - homepage.icon=mdi-key
      - homepage.href=https://${DOMAIN_AUTHENTIK:-authentik.pixelstack.live}
      - homepage.description=User Management
      - homepage.weight=20
      - homepage.widget.type=authentik
      - homepage.widget.fields=["users", "loginsLast24H", "failedLoginsLast24H"]
      - homepage.widget.url=https://${DOMAIN_AUTHENTIK:-authentik.pixelstack.live}}
      - homepage.widget.key=${HOMEPAGE_VAR_AUTHENTIK_KEY}

  auth-worker:
    image: ghcr.io/goauthentik/server:2025.8.1
    container_name: authentik-worker
    restart: always
    command: worker
    depends_on:
      - postgresql
      - valkey
    networks:
      - proxy
      - backend
    environment:
      AUTHENTIK_REDIS__HOST: valkey
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: ${DB_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${DB_NAME:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${DB_PASS}
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY}
      AUTHENTIK_EMAIL__HOST: ${AUTHENTIK_EMAIL_HOST}
      AUTHENTIK_EMAIL__PORT: ${AUTHENTIK_EMAIL_PORT}
      AUTHENTIK_EMAIL__USERNAME: ${AUTHENTIK_EMAIL_USERNAME}
      AUTHENTIK_EMAIL__PASSWORD: ${AUTHENTIK_EMAIL_PASSWORD}
      AUTHENTIK_EMAIL__USE_TLS: true
      AUTHENTIK_EMAIL__USE_SSL: false
      AUTHENTIK_EMAIL__TIMEOUT: 10
      AUTHENTIK_EMAIL__FROM: ${AUTHENTIK_EMAIL_FROM}
    volumes:
      - ${DIR_DATA}/authentik-data/media:/media
      - ${DIR_DATA}/authentik-data/templates:/templates
      - ${DIR_DATA}/authentik-data/certs:/certs

  auth-ldap:
    image: ghcr.io/goauthentik/ldap:2025.8.4
    container_name: authentik-ldap
    restart: always
    networks:
      - proxy
      - backend
    ports:
      - 389:3389
    #   - 636:6636
    environment:
      AUTHENTIK_HOST: https://auth-server:9443
      AUTHENTIK_INSECURE: "true"
      AUTHENTIK_TOKEN: ${LDAP_TOKEN}
    labels:
      # Traefik 3.0
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      # router: auth-ldap
      - "traefik.tcp.routers.auth-ldap.entrypoints=auth-ldap"
      - "traefik.tcp.routers.auth-ldap.rule=HostSNI(`${DOMAIN_AUTHENTIK_LDAP:-ldap.pixelstack.live}`)"
      - "traefik.tcp.routers.auth-ldap.middlewares=default-whitelist@file"
      - "traefik.tcp.routers.auth-ldap.service=auth-ldap"
      - "traefik.tcp.routers.auth-ldap.tls=true"
      - "traefik.tcp.routers.auth-ldap.tls.certresolver=${CERT_RESOLVER:-production}" # staging or production
      # service: auth-ldap
      - "traefik.tcp.services.auth-ldap.loadbalancer.server.port=3389"

networks:
  proxy:
    external: true
  backend: {}
