---

title: {{HOMEPAGE_VAR_TITLE}}
startUrl: {{HOMEPAGE_VAR_START_URL}}
background:
  image: https://images.unsplash.com/photo-1572208892098-d106c3bff8b1?q=80&w=2670&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
#  blur: sm
  opacity: 60
theme: dark
color: slate
language: en
target: _self
headerStyle: clean

quicklaunch:
  searchDescriptions: false
  hideInternetSearch: false
  showSearchSuggestions: true
  hideVisitURL: false

layout:
  - General:
  - Development:
  - University:
  - Shopping:
  - Shire:
      style: row
      columns: 1
      header: true
  - Shire-extra:
      header: false
  - Storage:
      header: false
  - Workspace:
      style: row
      initiallyCollapsed: true
      header: true
  - Calender:
      header: false
  - Management:
      header: false
  - Divider-2:
      style: row
      initiallyCollapsed: true
      header: false
  - Services:
      header: false
  - Providers:
      header: false
  - Networking:
      header: false

