# Title: Jellyfin
# Description: Media server

services:
  jellyfin:
    image: ghcr.io/linuxserver/jellyfin@sha256:747bc6725c5e4f1330e693b50d787e2106e52ac5b25c4174ca5f58915fc17ec8
    container_name: jellyfin
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-i", "http://127.0.0.1:8096/health"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 10s
    # network_mode: 'host'
    networks:
      - proxy
    # ports:
    #   - 8096:8096 # Http webUI
    #   - 8920:8920 # Https webUI (certificate required)
    #   - 7359:7359/udp # Jellyfin local network discovery
    #   - 1900:1900/udp # DNLA/service discovery
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-Europe/Berlin}
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /etc/hosts:/etc/hosts:ro
      - ${DIR_DATA}/cache:/cache
      - ${DIR_DATA}/config:/config
      - "${DIR_MOVIES}:/media/movies"
      - "${DIR_SERIES}:/media/series"
    labels:
      # Traefik 3.0
      - "traefik.enable=true"
      # router: jellyfin
      - "traefik.http.routers.jellyfin.entrypoints=https"
      - "traefik.http.routers.jellyfin.rule=Host(`${DOMAIN_JELLYFIN:-jellyfin.pixelstack.live}`)"
      - "traefik.http.routers.jellyfin.middlewares=jellyfin-headers,default-whitelist@file"
      - "traefik.http.routers.jellyfin.service=jellyfin"
      - "traefik.http.routers.jellyfin.tls=true"
      - "traefik.http.routers.jellyfin.tls.certresolver=${CERT_RESOLVER:-production}" # staging or production
      # service: jellyfin
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096" 
      - "traefik.http.services.jellyfin.loadbalancer.passHostHeader=true"
      # middleware: jellyfin-headers
      - "traefik.http.middlewares.jellyfin-headers.headers.frameDeny=true"
      - "traefik.http.middlewares.jellyfin-headers.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.jellyfin-headers.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.jellyfin-headers.headers.STSIncludeSubdomains=true"
      - "traefik.http.middlewares.jellyfin-headers.headers.STSPreload=true"
      - "traefik.http.middlewares.jellyfin-headers.headers.STSSeconds=315360000"
      - "traefik.http.middlewares.jellyfin-headers.headers.SSLRedirect=true"
      - "traefik.http.middlewares.jellyfin-headers.headers.SSLForceHost=true"
      - 'traefik.http.middlewares.jellyfin-mw.headers.SSLHost=${DOMAIN_JELLYFIN:-jellyfin.pixelstack.live}'
      - "traefik.http.middlewares.jellyfin-headers.headers.customFrameOptionsValue=SAMEORIGIN"
      - "traefik.http.middlewares.jellyfin-headers.headers.customResponseHeaders.X-Robots-Tag=noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex"
      - "traefik.http.middlewares.jellyfin-headers.headers.customresponseheaders.X-XSS-PROTECTION=1"
      # Homepage Dashboard
      - homepage.group=Services
      - homepage.name=Jellyfin
      - homepage.icon=jellyfin
      - homepage.href=https://${DOMAIN_JELLYFIN:-jellyfin.pixelstack.live}
      - homepage.description=Media Server
      - homepage.weight=40
      - homepage.widget.type=jellyfin
      - homepage.widget.fields=["movies", "series", "episodes", "songs"]
      - homepage.widget.url=https://${DOMAIN_JELLYFIN:-jellyfin.pixelstack.live}
      - homepage.widget.key=${HOMEPAGE_VAR_JELLYFIN_KEY}
      - homepage.widget.enableBlocks=true
      - homepage.widget.enableNowPlaying=true

networks:
  proxy:
    external: true

