# Title: Minecraft
# Description: Minecraft server with Crafty web interface

services:
  crafty:
    image: registry.gitlab.com/crafty-controller/crafty-4:4.9.0
    container_name: crafty
    restart: always
    networks:
      - proxy
    environment:
      TZ: ${TZ:-Europe/Berlin}
    # ports:
    #   - "8443:8443"               # HTTPS
    #   - "8123:8123"               # DYNMAP
    #   - "19132:19132/udp"         # BEDROCK
    #   - "25500-25600:25500-25600" # MC SERV PORT RANGE
    volumes:
        - ${DIR_DATA}/crafty/backups:/crafty/backups
        - ${DIR_DATA}/crafty/logs:/crafty/logs
        - ${DIR_DATA}/crafty/servers:/crafty/servers
        - ${DIR_DATA}/crafty/config:/crafty/app/config
        - ${DIR_DATA}/crafty/import:/crafty/import
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 512M
    labels:
      # Traefik 3.0
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      # router: crafty
      - "traefik.http.routers.crafty.entrypoints=https"
      - "traefik.http.routers.crafty.rule=Host(`${DOMAIN_CRAFTY:-crafty.pixelstack.live}`)"
      - "traefik.http.routers.crafty.middlewares=secured@file"
      - "traefik.http.routers.crafty.service=crafty"
      - "traefik.http.routers.crafty.tls=true"
      - "traefik.http.routers.crafty.tls.certresolver=${CERT_RESOLVER:-production}" # staging or production
      # router: minecraft
      - "traefik.tcp.routers.minecraft.entrypoints=minecraft"
      - "traefik.tcp.routers.minecraft.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.minecraft.service=minecraft"
      # service: crafty
      - "traefik.http.services.crafty.loadbalancer.server.scheme=https"
      - "traefik.http.services.crafty.loadbalancer.server.port=8443"
      # service: minecraft
      - "traefik.tcp.services.minecraft.loadbalancer.server.port=25565"

networks:
  proxy:
    external: true